all:
	g++ -g -Wall -c main.cpp ./roomInfo/startRoom.cpp ./roomInfo/flavor.cpp ./playerInput/commandAssign.cpp ./playerInput/inputSplit.cpp ./global/globalFunk.cpp ./roomInfo/greenRoom.cpp ./combatModule/combatModule.cpp ./combatModule/globalFunctions.cpp ./dialogueModule/dialogueModule.cpp
	g++ -g -Wall -o main *.o