#include<iostream>
#include<thread>
#include "flavor.h"
#include "../global/globalFunk.h"
using namespace std;

void startRoomFlavor() {
	clear();
	cout << "A SMALL DROP OF WATER WAKES ME.  I AM LAYING ON A STONE FLOOR.  I TAKE A DEEP BREATH; STALE AIR FILLS MY LUNGS.  I CAN'T REMEMBER THE LAST TIME I'VE EATEN A WARM MEAL.  I PUSH MYSELF UP OFF OF THE MILDEWED STONE FLOOR AND LOOK AT MY SURROUNDINGS.  I CAN SEE A RUSTIC, WOODEN CHEST.  THE IRON FITTINGS THAT LINE THE CHEST ARE EMBEDDED WITH SCRATCHES AND DENTS.  WHATEVER IS IN THAT CHEST, IT'S IMPORTANT.  THE STONE WALLS LOOK SECURE, BUT THERE IS ONE STONE THAT APPEARS DIFFERENT FROM THE REST.  IT IS UNSETTLED IN THE WALL.  THERE IS A HEAVY WOOD DOOR LADEN WITH DEEP CLAW MARKS.\n\nI NEED TO FIND MY WAY OUT OF HERE BEFORE IT'S TOO LATE.  I'M NOT THE FIRST TO BE TRAPPED IN THIS ROOM.  I WON'T BE THE LAST.";
	cout << endl << endl;
	sleepMilli(10000);
	cout << "PRESS ENTER TO CONTINUE..." << endl;
	getchar();
}

void greenRoomFlavor() {
	clear();
	cout << "I PUT THE KEY INTO THE KEYHOLE AND TURN.  WITH A SATISFYING METALLIC CLICK, THE DOOR UNLOCKS.  I SET MY BARE FEET INTO THE COLD STONE FLOOR FIRMLY AND PUSH ON THE DOOR.  IT BEGRUDGINGLY SLIDES OPEN AND I'M BLINDED BY A BEAM OF LIGHT COMING FROM THE CEILING.\n\nTHE ONCE STONE ROOF HAS FALLEN APART AND THE SUN IS SHINING THROUGH THE OPEN HOLE.  I CAN FEEL THE SUN AND FRESH AIR ON MY FACE.  ROOTS AND GRASS HAVE OVERGROWN THE STONE FLOOR.  BRICKS ARE SCATTERED AMONG THE FOLIAGE.  LONG VINES HANG FROM THE HOLE IN THE CEILING.  THEY LOOK TOO SLIM TO HOLD MY WEIGHT, SO I DON'T THINK I WILL BE ABLE TO CLIMB OUT OF THIS ROOM.";
	cout << endl << endl;
	sleepMilli(10000);
	cout << "PRESS ENTER TO CONTINUE..." << endl;
	getchar();
}